export * from './presentation/navigation/registerFriends'
export * from './presentation/store/friendsSlice'
export * from './presentation/i18n/translations'
export * from './presentation/types/injection'
export * from './presentation/routes/routes'
