name: Auto Publish Package

on:
  push:
    branches:
      - main
      - development
      - feature/**

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '20'
         cache: 'yarn'
      
      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      # 🔥 AUTO VERSION LOGIC
      - name: Set Version
        id: version
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)

          CURRENT_VERSION=$(node -p "require('./package.json').version")

          echo "Current version: $CURRENT_VERSION"

          if [ "$BRANCH" = "main" ]; then
            npm version patch --no-git-tag-version
            TAG="latest"

          elif [ "$BRANCH" = "development" ]; then
            NEW_VERSION="${CURRENT_VERSION}-beta.${GITHUB_RUN_NUMBER}"
            npm version $NEW_VERSION --no-git-tag-version
            TAG="beta"

          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            NEW_VERSION="${CURRENT_VERSION}-alpha.${SHORT_SHA}"
            npm version $NEW_VERSION --no-git-tag-version
            TAG="alpha"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Set dist-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          npm dist-tag add @LamNguyen17/sp-features-friends@$VERSION ${{ steps.version.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
